authors:
- Ansible
dependencies: {}
description: Bulk test collection tnsbabf21.tc966c4ea2 (based on ansible.utils)
license:
- GPL-2.0-or-later
name: tc966c4ea2
namespace: tnsbabf21
readme: README.md
repository: https://github.com/test/tnsbabf21.tc966c4ea2
tags:
- networking
version: 6.0.2
